{
    "name": "HipsterShop${DEMO_NUMBER}-A-Ingress-Policy",
    "policyType": "ingress",
    "permissions": "allow",
    "designators": [
        {
            "designatorType": "wlid",
            "wlid": "wlid://cluster-HipsterShopCluster${DEMO_NUMBER}/namespace-prod/deployment-nginx-ingress"
        }
    ],
    "peers": [
        {
            "ipRanges": [
                {
                    "ipRangeStart": "0.0.0.0",
                    "ipRangeEnd": "255.255.255.255"
                }
            ],
            "portRanges": [],
            "ports": [30000],
            "hosts": [],
            "isCertificateMandatory": false,
            "tlsCertificateProperties": {
                "commonName": "",
                "SANs": [],
                "organizationName": "",
                "issuerCN": "",
                "issuerCertificateID": "",
                "v3CustomeExtensions": {}
            }
        }
    ]
}

