{
    "name": "HipsterShop-A-Ingress-Policy",
    "attributes": null,
    "policyType": "ingress",
    "permissions": "allow",
    "enforcementAction": "block",
    "permissiveMode": True,
    "serverList": [
        {
            "designatorType": "attribute",
            "wlid": "",
            "wildwlid": "",
            "groupName": "",
            "ports": [],
            "attributes": {
                "app": "nginx-ingress",
                "cluster": "HipsterShopCluster"
            }
        }
    ],
    "clientList": [
        {
            "designatorType": "attribute",
            "wlid": "",
            "wildwlid": "",
            "attributes": {
                "app": "adservice",
                "cluster": "HipsterShopCluster"
            }
        }
    ]
}
